### ISSUE TITLE
Higher Resolution than 800x800 | Error

### ISSUE THREAD

**Issue by dexception** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#23]
```
2019-09-17 18:53:47: step600    image_name:b'1fda64fa-9177-4d4c-85ab-e7fe3b24205e_8192_8448.jpg' |	
                                                    rpn_loc_loss:0.00041194085497409105 |	 rpn_cla_loss:0.014123281463980675 |	
                                                    rpn_total_loss:0.014535222202539444 |
                                                    fast_rcnn_loc_loss:0.9085025787353516 |	 fast_rcnn_cla_loss:0.3403014838695526 |	
                                                    fast_rcnn_loc_rotate_loss:3.0595319271087646 |	 fast_rcnn_cla_rotate_loss:0.3519010841846466 |	
                                                    fast_rcnn_total_loss:4.6602373123168945 |	 attention_loss:0.006253000348806381 |	
                                                    total_loss:5.2554850578308105 |	 pre_cost_time:0.6669280529022217s
2019-09-17 18:54:22.683145: W tensorflow/core/framework/op_kernel.cc:1389] Invalid argument: ValueError: could not broadcast input array from shape (4) into shape (0)
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/detection_oprations/proposal_target_layer.py", line 35, in proposal_target_layer
    fg_rois_per_image, rois_per_image, cfgs.CLASS_NUM+1)

  File "../libs/detection_oprations/proposal_target_layer.py", line 179, in _sample_rois
    _get_bbox_regression_labels_h(bbox_target_data_h, num_classes)

  File "../libs/detection_oprations/proposal_target_layer.py", line 62, in _get_bbox_regression_labels_h
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]

ValueError: could not broadcast input array from shape (4) into shape (0)


2019-09-17 18:54:22.687491: W tensorflow/core/kernels/queue_base.cc:277] _0_get_batch/input_producer: Skipping cancelled enqueue attempt with queue not closed
2019-09-17 18:54:22.687581: W tensorflow/core/kernels/queue_base.cc:277] _1_get_batch/batch/padding_fifo_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: could not broadcast input array from shape (4) into shape (0)
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/detection_oprations/proposal_target_layer.py", line 35, in proposal_target_layer
    fg_rois_per_image, rois_per_image, cfgs.CLASS_NUM+1)

  File "../libs/detection_oprations/proposal_target_layer.py", line 179, in _sample_rois
    _get_bbox_regression_labels_h(bbox_target_data_h, num_classes)

  File "../libs/detection_oprations/proposal_target_layer.py", line 62, in _get_bbox_regression_labels_h
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]

ValueError: could not broadcast input array from shape (4) into shape (0)


	 [[{{node sample_RCNN_minibatch/PyFunc}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 230, in <module>
    train()
  File "train.py", line 180, in train
    _, global_stepnp = sess.run([train_op, global_step])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: could not broadcast input array from shape (4) into shape (0)
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/detection_oprations/proposal_target_layer.py", line 35, in proposal_target_layer
    fg_rois_per_image, rois_per_image, cfgs.CLASS_NUM+1)

  File "../libs/detection_oprations/proposal_target_layer.py", line 179, in _sample_rois
    _get_bbox_regression_labels_h(bbox_target_data_h, num_classes)

  File "../libs/detection_oprations/proposal_target_layer.py", line 62, in _get_bbox_regression_labels_h
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]

ValueError: could not broadcast input array from shape (4) into shape (0)


	 [[node sample_RCNN_minibatch/PyFunc (defined at ../libs/networks/build_whole_network.py:403) ]]

Caused by op 'sample_RCNN_minibatch/PyFunc', defined at:
  File "train.py", line 230, in <module>
    train()
  File "train.py", line 73, in train
    mask_batch=mask_batch[0])
  File "../libs/networks/build_whole_network.py", line 403, in build_whole_detection_network
    [tf.float32, tf.float32, tf.float32, tf.float32])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 468, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 282, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 151, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): ValueError: could not broadcast input array from shape (4) into shape (0)
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 207, in __call__
    ret = func(*args)

  File "../libs/detection_oprations/proposal_target_layer.py", line 35, in proposal_target_layer
    fg_rois_per_image, rois_per_image, cfgs.CLASS_NUM+1)

  File "../libs/detection_oprations/proposal_target_layer.py", line 179, in _sample_rois
    _get_bbox_regression_labels_h(bbox_target_data_h, num_classes)

  File "../libs/detection_oprations/proposal_target_layer.py", line 62, in _get_bbox_regression_labels_h
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]

ValueError: could not broadcast input array from shape (4) into shape (0)


	 [[node sample_RCNN_minibatch/PyFunc (defined at ../libs/networks/build_whole_network.py:403) ]]

```

**Comment by lifei1229** [comment]
Hello, how do you solve it? I also encountered this problem.
