### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by kongbia** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#36]
在测试demo_rh_pyramid.py中出现如下错误

Traceback (most recent call last):
  File "demo_rh_pyramid.py", line 393, in <module>
    args.h_overlap, args.w_overlap,  args.save_res)
  File "demo_rh_pyramid.py", line 69, in inference
    mask_batch=None)
  File "../libs/networks/build_whole_network.py", line 447, in build_whole_detection_network
    img_shape=img_shape)
  File "../libs/networks/build_whole_network.py", line 157, in postprocess_fastrcnn_r
    use_gpu=cfgs.ROTATE_NMS_USE_GPU)
  File "../libs/box_utils/nms_rotate.py", line 31, in nms_rotate
    device_id=gpu_id)
  File "../libs/box_utils/nms_rotate.py", line 112, in nms_rotate_gpu
    Tout=tf.int64)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 384, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 199, in _internal_py_func
    token = _py_funcs.insert(func)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 100, in insert
    self._funcs[token] = func
  File "/usr/lib/python2.7/weakref.py", line 108, in __setitem__
    self.data[key] = KeyedRef(value, self._remove, key)
  File "/usr/lib/python2.7/weakref.py", line 278, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object

**Comment by yangxue0827** [comment]
这个我也不清楚，你尝试调整一下环境，和我保持一致？
@kongbia

**Comment by HMCBSJ** [comment]
I had the same problem and solved it by downgrading TensorFlow to 1.2.0 (CPU version for me. Because I have Cuda 10 installed, GPU version doesn't work.. ) Check your compatible version here: https://www.tensorflow.org/install/source.

Now I have another problem when training.
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

I will check here first.. --> https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/issues/5
