### ISSUE TITLE
AssertionError: please set score threshold (example: SHOW_SCORE_THRSHOLD = 0.00) in cfgs.py

### ISSUE THREAD

**Issue by SumanthReddyKaliki** [DetectionTeamUCAS/R2CNN-Plus-Plus_Tensorflow#50]
Hi, 
I'm trying to run the demo code and I followed all the step that you mentioned in the Markdown. But I keep on getting this error

```
python demo_rh.py --src_folder='/content/drive/My Drive/R2CNN-Plus-Plus/data/test/' --image_ext='.png' --des_folder='/content/drive/My Drive/R2CNN-Plus-Plus/output/' --save_res=False --gpu='0'

/content/drive/My Drive/R2CNN-Plus-Plus/tools
demo.py		 demo_rh.py	     eval.py		inference.py  train.py
demo_pyramid.py  demo_rh_pyramid.py  icdar2015_eval.py	__init__.py
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--
/content/drive/My Drive/R2CNN-Plus-Plus
WARNING:tensorflow:From ../libs/networks/mobilenet/mobilenet.py:356: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

Traceback (most recent call last):
  File "demo_rh.py", line 380, in <module>
    200, 200, False)
  File "demo_rh.py", line 55, in inference
    'please set score threshold (example: SHOW_SCORE_THRSHOLD = 0.00) in cfgs.py'
AssertionError: please set score threshold (example: SHOW_SCORE_THRSHOLD = 0.00) in cfgs.py
```

But when I go and set the SHOW_SCORE_THRSHOLD to 0 in the cfgs.py I'm getting different error. 

```
Traceback (most recent call last):
  File "demo_rh.py", line 380, in <module>
    200, 200, False)
  File "demo_rh.py", line 69, in inference
    mask_batch=None)
  File "../libs/networks/build_whole_network.py", line 311, in build_whole_detection_network
    feature_to_cropped, C4_attention_layer = self.build_base_network(input_img_batch)
  File "../libs/networks/build_whole_network.py", line 38, in build_base_network
    return resnet.resnet_base(input_img_batch, scope_name=self.base_network_name, is_training=self.is_training)
  File "../libs/networks/resnet.py", line 150, in resnet_base
    C4_attention_layer = build_attention(C4, is_training)
  File "../libs/networks/attention.py", line 178, in build_attention
    weights_initializer=cfgs.INITIALIZER,
NameError: name 'cfgs' is not defined
```

**Comment by HMCBSJ** [comment]
I had a same problem and solved it by opening attention.py file then add "from libs.configs import cfgs "
 for the error below, open cfgs file then set SHOW_SCORE_THRSHOLD under 0.005
AssertionError: please set score threshold (example: SHOW_SCORE_THRSHOLD = 0.00) in cfgs.py

**Comment by hopesala** [comment]
@HMCBSJ thanks you. it solved my same error.
